name: Gatsby Publish

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GATRACKINGID:  ${{ secrets.GATRACKINGID }}
          AWCONVERSIONID:  ${{ secrets.AWCONVERSIONID }}
          DCFLOODIGHTID:  ${{ secrets.DCFLOODIGHTID }}
          ENV_TEST: ${{ secrets.ENV_TEST }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
     
